Verbatim duplicate the MYSQL functions for POSTGRES

diff --git a/bin/fin b/bin/fin
--- a/bin/fin
+++ b/bin/fin
@@ -5914,6 +5914,287 @@ mysql_dump ()
 	fi
 }
 
+# Start interactive psql shell
+# --db-user="admin" to override psql username
+# --db-password="otherpass" to override psql password
+# --db="drupal" to override database (only applies to queries)
+_psql ()
+{
+	check_winpty_found
+	check_docksal_environment
+	eval $(parse_params "$@")
+
+	# Bring in POSTGRES env variables from the db container, so that we can use them here
+	container_id=$(get_project_container_id "db")
+	container_psql_vars=$(docker exec "$container_id" env | grep "^POSTGRES_")
+	eval ${container_psql_vars}
+
+	local __dump_user="${dbuser:-root}"
+	# POSTGRES_* variable expansion happens here
+	local __dump_password="${dbpassword:-$POSTGRES_ROOT_PASSWORD}"
+	local __database="${db:-$POSTGRES_DATABASE}"
+	local __pty_command=''
+	if is_tty || [[ -z "${ARGV[*]}" ]]; then
+		__pty_command="${winpty}"
+	fi
+	local __pty_alloc=''
+	if is_tty; then
+		__pty_alloc='-t'
+	fi
+
+	${__pty_command} docker exec -i ${__pty_alloc} "${container_id}" psql \
+		-u"${__dump_user}" \
+		-p"${__dump_password}" \
+		${__database} \
+		${ARGV:+-e "${ARGV[*]}"}
+}
+
+# Show databases list
+# --db-user="admin" to override psql username
+# --db-password="otherpass" to override psql password
+psql_list ()
+{
+	check_project_environment
+	eval $(parse_params "$@")
+
+	# Bring in POSTGRES env variables from the db container, so that we can use them here
+	container_id=$(get_project_container_id "db")
+	container_psql_vars=$(docker exec "$container_id" env | grep "^POSTGRES_")
+	eval ${container_psql_vars}
+
+	local __dump_user="${dbuser:-root}"
+	local __dump_password="${dbpassword:-$POSTGRES_ROOT_PASSWORD}"
+
+	# -N parameter suppresses columns header
+	_exec --in="db" "echo 'SHOW DATABASES' | psql -N -u ${__dump_user} -p${__dump_password}"
+}
+
+# Create a database
+# --db-user="admin" to override psql username
+# --db-password="otherpass" to override psql password
+# --db-charset="..." to override charset (default is utf8)
+# --db-collation="..." to override collation (default is utf8_general_ci)
+psql_db_create ()
+{
+	check_project_environment
+	eval $(parse_params "$@")
+
+	# Bring in POSTGRES env variables from the db container, so that we can use them here
+	container_id=$(get_project_container_id "db")
+	container_psql_vars=$(docker exec "$container_id" env | grep "^POSTGRES_")
+	eval ${container_psql_vars}
+
+	local __dump_user="${dbuser:-root}"
+	local __dump_password="${dbpassword:-$POSTGRES_ROOT_PASSWORD}"
+	local __db="${ARGV[0]}"
+	local __db_charset="${dbcharset:-utf8mb4}"
+	local __db_collation="${dbcollation:-utf8mb4_unicode_ci}"
+
+	[[ "${__db}" == "" ]] && echo-error "Provide a name for the database to create" && exit 1
+
+	# Set db to space since the db does not exist here yet
+	(_psql --db=" " --db-user="${__dump_user}" --db-password="${__dump_password}" \
+		"CREATE DATABASE IF NOT EXISTS \`${__db}\` CHARACTER SET ${__db_charset} COLLATE ${__db_collation};") &&
+		# GRANT ALL has to happen in a separate query, otherwise we will be hitting a race condition (when db is not yet created).
+		(_psql --db="${__db}" --db-user="${__dump_user}" --db-password="${__dump_password}" \
+		"GRANT ALL PRIVILEGES ON \`${__db}\`.* TO \`${POSTGRES_USER}\`;")
+
+	if_failed_error "Database '${__db}' creation failed"
+
+	echo -e "Database ${yellow}${__db}${NC} created"
+}
+
+# Delete a database
+# --db-user="admin" to override psql username
+# --db-password="otherpass" to override psql password
+psql_db_drop ()
+{
+	check_project_environment
+	eval $(parse_params "$@")
+
+	# Bring in POSTGRES env variables from the db container, so that we can use them here
+	container_id=$(get_project_container_id "db")
+	container_psql_vars=$(docker exec "$container_id" env | grep "^POSTGRES_")
+	eval ${container_psql_vars}
+
+	local __dump_user="${dbuser:-root}"
+	local __dump_password="${dbpassword:-$POSTGRES_ROOT_PASSWORD}"
+	local __db="${ARGV[0]}"
+
+	[[ "${__db}" == "" ]] && echo-error "Provide the name of the database to drop." && exit 1
+
+	_psql --db=" " --db-user="${__dump_user}" --db-password="${__dump_password}" \
+		"DROP DATABASE IF EXISTS \`${__db}\`"
+
+	if_failed_error "Dropping '${__db}' database failed"
+	echo -e "Database ${yellow}${__db}${NC} dropped"
+}
+
+# Truncate db
+# @params
+# $1 - database name
+# --db-user="admin" to override psql username
+# --db-password="otherpass" to override psql password
+psql_db_truncate ()
+{
+	check_project_environment
+	eval $(parse_params "$@")
+
+	# Bring in POSTGRES env variables from the db container, so that we can use them here
+	container_id=$(get_project_container_id "db")
+	container_psql_vars=$(docker exec "$container_id" env | grep "^POSTGRES_")
+	eval ${container_psql_vars}
+
+	local __dump_user="${dbuser:-root}"
+	local __dump_password="${dbpassword:-$POSTGRES_ROOT_PASSWORD}"
+	local __database="${1:-${POSTGRES_DATABASE:-default}}"
+
+	echo -e "Truncating ${yellow}${__database}${NC} database..."
+	read -r -d '' DBCREATE_COMMAND <<-EOF
+		SELECT
+			DEFAULT_CHARACTER_SET_NAME, DEFAULT_COLLATION_NAME
+			INTO
+				@_charset, @_collation FROM information_schema.schemata
+			WHERE
+				schema_name = '${__database}';
+		SET @CREATE_TEMPLATE = 'CREATE DATABASE \\\`{DBNAME}\\\` CHARACTER SET {DBCHARSET} COLLATE {DBCOLLATION};';
+		SET @SQL_SCRIPT = REPLACE(@CREATE_TEMPLATE, '{DBNAME}', '${__database}');
+		SET @SQL_SCRIPT = REPLACE(@SQL_SCRIPT, '{DBCHARSET}', @_charset);
+		SET @SQL_SCRIPT = REPLACE(@SQL_SCRIPT, '{DBCOLLATION}', @_collation);
+		PREPARE DBCREATE FROM @SQL_SCRIPT;
+		DROP DATABASE \\\`${__database}\\\`;
+		EXECUTE DBCREATE;
+	EOF
+	_exec --in="db" "echo -e \"$DBCREATE_COMMAND\"| psql -u${__dump_user} -p${__dump_password} ${__database} "
+}
+
+# Truncate db and import from sql dump
+# @params
+# $1 - file name
+# --db="drupal" to override database username
+# --db-user="admin" to override psql username
+# --db-password="otherpass" to override psql password
+# --no-truncate to avoid truncate
+psql_import ()
+{
+	check_project_environment
+	eval $(parse_params "$@")
+
+	# Bring in POSTGRES env variables from the db container, so that we can use them here
+	container_id=$(get_project_container_id "db")
+	container_psql_vars=$(docker exec "$container_id" env | grep "^POSTGRES_")
+	eval ${container_psql_vars}
+
+	local __dump_user="${dbuser:-root}"
+	local __dump_password="${dbpassword:-$POSTGRES_ROOT_PASSWORD}"
+	local __database="${db:-${POSTGRES_DATABASE:-default}}"
+	# /dev/fd/0 is the stdin stream for current script
+	# IMPORTANT: don't run "docker exec" with "-i" until value of /dev/fd/0 is used or its value will be lost
+	local __input="${ARGV[0]:-/dev/fd/0}"
+
+	[[ "${__input}" != "/dev/fd/0" ]] && [[ ! -r "${__input}" ]] &&
+		echo-error "Can not read ${__input}" "Please check file path and permissions" && exit 1
+
+	local confirm=0
+	[[ "$force" == "force" ]] && confirm=1
+	# Use cat to pipe dump content by default
+	local pipe_cmd='cat'
+	# Show DB import progress if requested and pv binary is available
+	if [[ "$progress" == "progress" ]]; then
+		if (which 'pv' >/dev/null 2>&1); then
+			pipe_cmd='pv'
+		else
+			echo-yellow "Cannot display import progress: pv binary is needed, but missing."
+		fi
+	fi
+
+	#-- 1) RECREATE DATABASE WITH THE SAME CHARSET AND COLLATION
+	if [[ "$notruncate" != "notruncate" ]]; then
+		echo -e "Truncating ${yellow}${__database}${NC} database..."
+		read -r -d '' DBCREATE_COMMAND <<-EOF
+			SELECT
+				DEFAULT_CHARACTER_SET_NAME, DEFAULT_COLLATION_NAME
+				INTO
+					@_charset, @_collation FROM information_schema.schemata
+				WHERE
+					schema_name = '${__database}';
+			SET @CREATE_TEMPLATE = 'CREATE DATABASE \\\`{DBNAME}\\\` CHARACTER SET {DBCHARSET} COLLATE {DBCOLLATION};';
+			SET @SQL_SCRIPT = REPLACE(@CREATE_TEMPLATE, '{DBNAME}', '${__database}');
+			SET @SQL_SCRIPT = REPLACE(@SQL_SCRIPT, '{DBCHARSET}', @_charset);
+			SET @SQL_SCRIPT = REPLACE(@SQL_SCRIPT, '{DBCOLLATION}', @_collation);
+			PREPARE DBCREATE FROM @SQL_SCRIPT;
+			DROP DATABASE \\\`${__database}\\\`;
+			EXECUTE DBCREATE;
+		EOF
+		_exec --in="db" "echo -e \"$DBCREATE_COMMAND\"| psql -u${__dump_user} -p${__dump_password} ${__database} "
+
+		if [[ ! $? -eq 0 ]] && (exit ${confirm}); then
+			_confirm "There were errors during truncation. Continue anyways?"
+		fi
+	fi
+
+	#-- 2) IMPORTING
+	[[ "${__input}" != "/dev/fd/0" ]] &&
+		echo -e "Importing ${yellow}$(basename ${__input})${NC}..." ||
+		echo "Importing from stdin..."
+	# We can not use _run here because we need to launch docker exec with only -i param
+	# and only psql command directly (no bash wrapper) so that stdin could be received inside that exec
+	container_id=$(get_project_container_id "db")
+	__psql_command=$(docker exec "$container_id" bash -c "echo -u${__dump_user} -p${__dump_password}")
+	__psql_command=$(echo "${__psql_command}" | sed -e 's/[^a-zA-Z0-9_-]$//')
+	# "docker exec -i" is required as it creates stdin/stdout streams but does not create tty
+	${pipe_cmd} "${__input}" | docker exec -i ${container_id} psql ${__psql_command} ${__database}
+
+	# Check if import succeeded or not and print results.
+	if [ $? -eq 0 ]; then
+		echo-green "Done"
+		exit 0
+	else
+		echo-red "Import failed"
+		exit 1
+	fi
+}
+
+# Dump psql database
+# @params
+# $1 - file name, if ommitted then stdout
+# --db="drupal" to override database username
+# --db-user="admin" to override psql username
+# --db-password="otherpass" to override psql password
+psql_dump ()
+{
+	check_project_environment
+	eval $(parse_params "$@")
+
+	# Bring in POSTGRES env variables from the db container, so that we can use them here
+	container_id=$(get_project_container_id "db")
+	container_psql_vars=$(docker exec "$container_id" env | grep "^POSTGRES_")
+	eval ${container_psql_vars}
+
+	local __dump_user="${dbuser:-root}"
+	local __dump_password="${dbpassword:-$POSTGRES_ROOT_PASSWORD}"
+	local __database="${db:-${POSTGRES_DATABASE:-default}}"
+	local __output="${ARGV[0]}"
+
+	if [[ "${ARGV[0]}" != "" ]]; then
+		touch "${__output}"
+		if_failed_error "Could not write ${__output}" "Please check your file permissions"
+		echo-green "Exporting..."
+	fi
+
+	container_id=$(get_project_container_id "db")
+	__psql_command=$(docker exec -i "$container_id" bash -c "echo -u${__dump_user} -p${__dump_password}")
+	if [[ "${ARGV[0]}" == "" ]]; then
+		docker exec -i "$container_id" psqldump ${__psql_command} ${__database}
+	else
+		docker exec -i "$container_id" psqldump ${__psql_command} ${__database} | tee "${__output}" >/dev/null
+	fi
+
+	if [[ "${ARGV[0]}" != "" ]]; then
+		[ $? -eq 0 ] && echo "Done."
+	fi
+}
+
 # Download script by URL and execute it
 # @param $1 url of script.
 exec_url ()
